W0107 21:22:32.383990 140108548702592 __init__.py:484] Setting up a new session...
W0107 21:22:32.393094 140106516317952 _logging.py:66] websocket connected
I0107 21:22:32.393960 140106516317952 __init__.py:569] Visdom successfully connected to server


100%|██████████| 31668/31668 [00:04<00:00, 7453.06it/s]


























































































































































































































































































































































































































































































































































































































































































































































































































































































































100%|██████████| 4061/4061 [30:01<00:00,  2.25it/s]

  1%|          | 1/124 [00:07<15:33,  7.59s/it]/share/share_40t/baoyanghao/DGCN/diversified_candidate_generation/metrics.py:147: RuntimeWarning: invalid value encountered in long_scalars
  return hit_count/num_test_pos

























































































































100%|██████████| 124/124 [17:57<00:00,  8.69s/it]


































































































































































































































































 21%|██▏       | 870/4061 [08:39<31:43,  1.68it/s]
Traceback (most recent call last):
  File "app.py", line 76, in <module>
    app.run(main)
  File "/share/share_40t/baoyanghao/anaconda3/envs/dgcngpupy37/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/share/share_40t/baoyanghao/anaconda3/envs/dgcngpupy37/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "app.py", line 70, in main
    trainer.train()
  File "/share/share_40t/baoyanghao/DGCN/diversified_candidate_generation/trainer.py", line 51, in train
    self.train_one_epoch(epoch)
  File "/share/share_40t/baoyanghao/DGCN/diversified_candidate_generation/trainer.py", line 133, in train_one_epoch
    self.optimizer.zero_grad()
  File "/share/share_40t/baoyanghao/anaconda3/envs/dgcngpupy37/lib/python3.7/site-packages/torch/optim/optimizer.py", line 249, in zero_grad
    p.grad.zero_()
KeyboardInterrupt